name: 'Frontend Continuous Deployment'
on:
  workflow_dispatch:
  
  push:
    branches:
      - main

env:
  NODE_VERSION: '22.0.0'
  AWS_REGION: 'us-east-1'
  REACT_APP_MOVIE_API_URL: 'frontend.default.svc.cluster.local:5000'


jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest   # Use the latest Ubuntu runner

    steps:
      # Check out the code to the runner
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.Js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Install npm dependency
        run: cd frontend && npm ci

      - name: run test
        run: cd frontend && npm test

  build:
    name: 'Build'
    needs: [test]
    runs-on: ubuntu-latest   # Use the latest Ubuntu runner

    steps:
      # Check out the code to the runner
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.Js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Install npm dependency
        run: cd frontend && npm ci

      - name: build 
        run: cd frontend && npm run build